server:
    port: 8001

spring:
    application:
        name: demo1-service
    profiles:
        active: dev
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.1.114:8848

swagger:
    enabled: true

#提升nacos配置中心的打印日志级别(其实是nacos的一个bug)，禁止打印无用信息
logging:
    level:
        com.alibaba.nacos.client.config.impl: WARN